### ISSUE TITLE
using argparse module for command line arguments for the scripts  

### ISSUE THREAD

**Issue by hadyelsahar** [hadyelsahar/OpenIE#1]
for cleaner interface and in order not to change the file input and output paths please add the input file and output file as arguments to the script, using the argparse module 
https://docs.python.org/3/library/argparse.html

example : https://github.com/hadyelsahar/large-arabic-multidomain-lexicon/blob/master/featureselection.py#L26

**Comment by hbenarab** [comment]
Done !!
